cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"

matrix:
  include:
    - os: linux
      python: 3.5
      language: python
    - os: linux
      dist: trusty
      python: 3.6
      language: python
    - os: osx
      osx_image: xcode7.3
      language: generic
    - os: osx
      osx_image: xcode8.2
      language: generic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install python3; fi

install:
  - pip3 install -r requirements.txt
  - python3 setup.py install

script:
  - cp accounts.example.csv accounts.csv
  - python3 scripts/create_db.py
  - python3 -c 'from monocle import avatar, bounds, db_proc, db, names, notification, overseer, sanitized, shared, spawns, utils, web_utils, worker'
